global:
  external_labels:
      monitor: 'rabbitmq-monitor'

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rabbitmq'
    scrape_interval: 10s
    metrics_path: /api/metrics
    static_configs:
      - targets: ['rabbitmq:15672']